### ISSUE TITLE
Please update the doc to mention how to use Artifactory item storage with job cacher plugin in pipeline

### ISSUE THREAD

**Issue by ravindrakmr** [jenkinsci/jobcacher-artifactory-storage-plugin#18]
### Describe your use-case which is not covered by existing documentation.

My confusion is what should be the value of path attribute in pipeline if we use item storage as Artifactory - 
cache(maxCacheSize: 2048, caches: [
            arbitraryFileCache(
                **path: "mypath",**
                includes: "**/*",
                cacheValidityDecidingFile: "next-lock.cache"
            )
            ])
For every value , it is giving - Cannot create cache as the path does not exist. Please note I have already configured Artifactory as item storage in my Jenkins global configuration. Any help would be highly appreciated. Thanks

**Comment by jonesbusy** [comment]
There is no change at pipeline level. Just configure the plugin via UI or JcasC. This is most likely that the path is not found on workspace.

If it's still an issue check on jobcacher plugin for usage
